components {
  id: "particlefx"
  component: "/enemy/enemy_death.particlefx"
}
components {
  id: "particlefx_light"
  component: "/enemy/light.particlefx"
}
components {
  id: "script"
  component: "/level/level.script"
}
embedded_components {
  id: "blur"
  type: "model"
  data: "mesh: \"/materials/quad.gltf\"\n"
  "materials {\n"
  "  name: \"lambert1_004\"\n"
  "  material: \"/materials/blur.material\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"level\"\n"
  "mask: \"player\"\n"
  "mask: \"enemy\"\n"
  "mask: \"bullet\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 1.187844\n"
  "      y: 314.62314\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 1191.1879\n"
  "      y: 314.62314\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 596.18787\n"
  "      y: -0.37687582\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 6\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 596.18787\n"
  "      y: 629.6231\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 9\n"
  "    count: 3\n"
  "  }\n"
  "  data: 5.0\n"
  "  data: 320.0\n"
  "  data: 10.0\n"
  "  data: 5.0\n"
  "  data: 320.0\n"
  "  data: 10.0\n"
  "  data: 600.0\n"
  "  data: 5.0\n"
  "  data: 10.0\n"
  "  data: 600.0\n"
  "  data: 5.0\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "grid"
  type: "model"
  data: "mesh: \"/level/grid6.gltf\"\n"
  "materials {\n"
  "  name: \"Default_Material_001\"\n"
  "  material: \"/level/grid.material\"\n"
  "}\n"
  "create_go_bones: false\n"
  ""
}
embedded_components {
  id: "sound"
  type: "sound"
  data: "sound: \"/level/overloadshortmaster.wav\"\n"
  ""
}
embedded_components {
  id: "quad"
  type: "model"
  data: "mesh: \"/materials/quad.gltf\"\n"
  "materials {\n"
  "  name: \"lambert1_004\"\n"
  "  material: \"/materials/quad.material\"\n"
  "}\n"
  ""
}
