components {
  id: "particlefx"
  component: "/enemy/black_hole.particlefx"
}
components {
  id: "script"
  component: "/enemy/black_hole.script"
}
embedded_components {
  id: "background"
  type: "sprite"
  data: "default_animation: \"background\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/enemy/black_hole.tilesource\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "body"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"black_hole\"\n"
  "mask: \"enemy\"\n"
  "mask: \"bullet\"\n"
  "mask: \"player\"\n"
  "mask: \"sensor\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "  }\n"
  "  data: 25.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "foreground"
  type: "sprite"
  data: "default_animation: \"foreground\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/enemy/black_hole.tilesource\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "light_mask"
  type: "sprite"
  data: "default_animation: \"anim\"\n"
  "material: \"/materials/light_mask.material\"\n"
  "textures {\n"
  "  sampler: \"DIFFUSE_TEXTURE\"\n"
  "  texture: \"/enemy/light_mask.tilesource\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "sensor"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"sensor\"\n"
  "mask: \"enemy\"\n"
  "mask: \"bullet\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "  }\n"
  "  data: 250.0\n"
  "}\n"
  ""
}
